// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
import type { ComponentMeta } from "./types";
import accordionMeta from "../components/accordion/meta";
import alertMeta from "../components/alert/meta";
import avatarMeta from "../components/avatar/meta";
import badgeMeta from "../components/badge/meta";
import breadcrumbsMeta from "../components/breadcrumbs/meta";
import buttonMeta from "../components/button/meta";
import cardMeta from "../components/card/meta";
import checkboxMeta from "../components/checkbox/meta";
import dialogMeta from "../components/dialog/meta";
import drawerMeta from "../components/drawer/meta";
import dropdownMenuMeta from "../components/dropdown-menu/meta";
import iconButtonMeta from "../components/icon-button/meta";
import inputMeta from "../components/input/meta";
import kbdMeta from "../components/kbd/meta";
import paginationMeta from "../components/pagination/meta";
import progressMeta from "../components/progress/meta";
import radioGroupMeta from "../components/radio-group/meta";
import segmentedControlMeta from "../components/segmented-control/meta";
import selectMeta from "../components/select/meta";
import separatorMeta from "../components/separator/meta";
import skeletonMeta from "../components/skeleton/meta";
import sliderMeta from "../components/slider/meta";
import spinnerMeta from "../components/spinner/meta";
import statMeta from "../components/stat/meta";
import switchMeta from "../components/switch/meta";
import tableMeta from "../components/table/meta";
import tabsMeta from "../components/tabs/meta";
import tagMeta from "../components/tag/meta";
import textareaMeta from "../components/textarea/meta";
import toastMeta from "../components/toast/meta";
import tooltipMeta from "../components/tooltip/meta";

export const catalog: ComponentMeta[] = [
  accordionMeta,
  alertMeta,
  avatarMeta,
  badgeMeta,
  breadcrumbsMeta,
  buttonMeta,
  cardMeta,
  checkboxMeta,
  dialogMeta,
  drawerMeta,
  dropdownMenuMeta,
  iconButtonMeta,
  inputMeta,
  kbdMeta,
  paginationMeta,
  progressMeta,
  radioGroupMeta,
  segmentedControlMeta,
  selectMeta,
  separatorMeta,
  skeletonMeta,
  sliderMeta,
  spinnerMeta,
  statMeta,
  switchMeta,
  tableMeta,
  tabsMeta,
  tagMeta,
  textareaMeta,
  toastMeta,
  tooltipMeta,
];

export const catalogBySlug: Record<string, ComponentMeta> = Object.fromEntries(
  catalog.map((m) => [m.slug, m]),
);

export const catalogSlugs = catalog.map((m) => m.slug);
