"use client";

// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
import * as React from "react";
import * as accordionDemo from "../components/accordion/Demo";
import * as alertDemo from "../components/alert/Demo";
import * as avatarDemo from "../components/avatar/Demo";
import * as badgeDemo from "../components/badge/Demo";
import * as breadcrumbsDemo from "../components/breadcrumbs/Demo";
import * as buttonDemo from "../components/button/Demo";
import * as cardDemo from "../components/card/Demo";
import * as checkboxDemo from "../components/checkbox/Demo";
import * as dialogDemo from "../components/dialog/Demo";
import * as drawerDemo from "../components/drawer/Demo";
import * as dropdownMenuDemo from "../components/dropdown-menu/Demo";
import * as iconButtonDemo from "../components/icon-button/Demo";
import * as inputDemo from "../components/input/Demo";
import * as kbdDemo from "../components/kbd/Demo";
import * as paginationDemo from "../components/pagination/Demo";
import * as progressDemo from "../components/progress/Demo";
import * as radioGroupDemo from "../components/radio-group/Demo";
import * as segmentedControlDemo from "../components/segmented-control/Demo";
import * as selectDemo from "../components/select/Demo";
import * as separatorDemo from "../components/separator/Demo";
import * as skeletonDemo from "../components/skeleton/Demo";
import * as sliderDemo from "../components/slider/Demo";
import * as spinnerDemo from "../components/spinner/Demo";
import * as statDemo from "../components/stat/Demo";
import * as switchDemo from "../components/switch/Demo";
import * as tableDemo from "../components/table/Demo";
import * as tabsDemo from "../components/tabs/Demo";
import * as tagDemo from "../components/tag/Demo";
import * as textareaDemo from "../components/textarea/Demo";
import * as toastDemo from "../components/toast/Demo";
import * as tooltipDemo from "../components/tooltip/Demo";

export interface DemoModule {
  Preview: React.ComponentType;
  Demo: React.ComponentType;
}

export const demos: Record<string, DemoModule> = {
  "accordion": accordionDemo,
  "alert": alertDemo,
  "avatar": avatarDemo,
  "badge": badgeDemo,
  "breadcrumbs": breadcrumbsDemo,
  "button": buttonDemo,
  "card": cardDemo,
  "checkbox": checkboxDemo,
  "dialog": dialogDemo,
  "drawer": drawerDemo,
  "dropdown-menu": dropdownMenuDemo,
  "icon-button": iconButtonDemo,
  "input": inputDemo,
  "kbd": kbdDemo,
  "pagination": paginationDemo,
  "progress": progressDemo,
  "radio-group": radioGroupDemo,
  "segmented-control": segmentedControlDemo,
  "select": selectDemo,
  "separator": separatorDemo,
  "skeleton": skeletonDemo,
  "slider": sliderDemo,
  "spinner": spinnerDemo,
  "stat": statDemo,
  "switch": switchDemo,
  "table": tableDemo,
  "tabs": tabsDemo,
  "tag": tagDemo,
  "textarea": textareaDemo,
  "toast": toastDemo,
  "tooltip": tooltipDemo,
};
